AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  PROJECT:
    Type: String
  ENVIRONMENT:
    Type: String
  STRIPEPUBLISHABLEKEY:
    Type: String
  STRIPESECRETKEY:
    Type: String
  STRIPEWEBHOOKSECRET:
    Type: String
  CONTENTFULSPACEID:
    Type: String
  CONTENTFULDELIVERYAPIACCESSTOKEN:
    Type: String

Mappings:
  dev:
    api:
      hostname: aws.triplehead.net
  prod:
    api:
      hostname: api.geja.se

Conditions:
  IsProd: !Equals [ !Ref ENVIRONMENT, prod ]

Globals:
  Function:
    Runtime: nodejs10.x
    Timeout: 30
    Handler: index.handler
    Tracing: Active
    Environment:
      Variables:
        API_BASE_PATH: !If
          - IsProd
          - ""
          - !Sub ${PROJECT}
        CONTENTFUL_SPACE_ID: !Sub ${CONTENTFULSPACEID}
        CONTENTFUL_DELIVERY_API_ACCESS_TOKEN: !Sub ${CONTENTFULDELIVERYAPIACCESSTOKEN}
        ENVIRONMENT: !Sub ${ENVIRONMENT}
        LOG_LEVEL: info
        PROJECT: !Sub ${PROJECT}

Resources:

  CartsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub ${PROJECT}-carts-${ENVIRONMENT}
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  OrderCreationSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub GEJA Orders (${ENVIRONMENT})
      KmsMasterKeyId: alias/aws/sns

  ContactRequestsSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub GEJA Contact Requests (${ENVIRONMENT})
      KmsMasterKeyId: alias/aws/sns

  # REST API
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${PROJECT}-${ENVIRONMENT}
      StageName: !Ref ENVIRONMENT
      Cors:
        AllowMethods: "'POST, GET, OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: swagger.yaml

  BasePath:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !If
        - IsProd
        - !Ref AWS::NoValue
        - !Sub ${PROJECT}
      DomainName: !FindInMap [!Ref ENVIRONMENT, api, hostname]
      RestApiId: !Ref ApiGateway
      Stage: !Ref ApiGateway.Stage

  ApiLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${PROJECT}-api-${ENVIRONMENT}
      CodeUri: dist/src/
      Handler: apiHandler.handler
      Environment:
        Variables:
          STRIPE_PUBLISHABLE_KEY: !Sub ${STRIPEPUBLISHABLEKEY}
          STRIPE_SECRET_KEY: !Sub ${STRIPESECRETKEY}
          STRIPE_WEBHOOK_SECRET: !Sub ${STRIPEWEBHOOKSECRET}
          ORDERS_TOPIC_ARN: !Ref OrderCreationSNSTopic
          CONTACTREQUESTS_TOPIC_ARN: !Ref ContactRequestsSNSTopic
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:PutItem
                - dynamodb:Scan
              Resource:
                - !Sub arn:aws:dynamodb:${AWS::Region}:*:table/${PROJECT}-*-${ENVIRONMENT}
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref OrderCreationSNSTopic
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref ContactRequestsSNSTopic

  ApiLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ApiLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

  ApiHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ApiLambda}
      RetentionInDays: 365

  # Order Confirmation Emails
  OrderConfirmationEmailsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${PROJECT}-orderconfirmationemails-${ENVIRONMENT}
      MessageRetentionPeriod: 1209600

  OrderConfirmationEmailsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    DependsOn:
    - OrderConfirmationEmailsQueue
    Properties:
      Queues:
      - !Ref OrderConfirmationEmailsQueue
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal:
            Service: sns.amazonaws.com
          Action:
          - sqs:SendMessage
          Resource: !GetAtt OrderConfirmationEmailsQueue.Arn
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref OrderCreationSNSTopic

  OrderConfirmationEmailsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt OrderConfirmationEmailsQueue.Arn
      Protocol: sqs
      RawMessageDelivery: false
      Region: !Sub ${AWS::Region}
      TopicArn: !Ref OrderCreationSNSTopic

  OrderConfirmationEmailsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${PROJECT}-orderconfirmationemails-${ENVIRONMENT}
      CodeUri: dist/src/
      Handler: orderConfirmationSender.handler
      Events:
        EmailSqsEvents:
          Type: SQS
          Properties:
            Queue: !GetAtt OrderConfirmationEmailsQueue.Arn
            BatchSize: 10
            Enabled: true
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:ChangeMessageVisibility
                - sqs:GetQueueAttributes
              Resource: !GetAtt OrderConfirmationEmailsQueue.Arn
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource:
                - !Sub arn:aws:dynamodb:${AWS::Region}:*:table/${PROJECT}-*-${ENVIRONMENT}
            - Effect: Allow
              Action:
                - "ses:SendEmail"
                - "ses:SendRawEmail"
              Resource: "*"
              Condition:
                StringLike:
                  "ses:FromAddress": "*@geja.se"

  OrderConfirmationEmailsHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${OrderConfirmationEmailsLambda}
      RetentionInDays: 365

  # Contact Emails
  ContactEmailsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${PROJECT}-contactemails-${ENVIRONMENT}
      MessageRetentionPeriod: 1209600

  ContactEmailsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    DependsOn:
    - ContactEmailsQueue
    Properties:
      Queues:
      - !Ref ContactEmailsQueue
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal:
            Service: sns.amazonaws.com
          Action:
          - sqs:SendMessage
          Resource: !GetAtt ContactEmailsQueue.Arn
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref ContactRequestsSNSTopic

  ContactEmailsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt ContactEmailsQueue.Arn
      Protocol: sqs
      RawMessageDelivery: false
      Region: !Sub ${AWS::Region}
      TopicArn: !Ref ContactRequestsSNSTopic

  ContactEmailsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${PROJECT}-contactemails-${ENVIRONMENT}
      CodeUri: dist/src/
      Handler: contactFormSender.handler
      Events:
        EmailSqsEvents:
          Type: SQS
          Properties:
            Queue: !GetAtt ContactEmailsQueue.Arn
            BatchSize: 10
            Enabled: true
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:ChangeMessageVisibility
                - sqs:GetQueueAttributes
              Resource: !GetAtt ContactEmailsQueue.Arn
            - Effect: Allow
              Action:
                - "ses:SendEmail"
                - "ses:SendRawEmail"
              Resource: "*"
              Condition:
                StringLike:
                  "ses:FromAddress": "*@geja.se"

  ContactEmailsHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ContactEmailsLambda}
      RetentionInDays: 365
