version: 2
jobs:
  test:
    docker:
      - image: sleavely/node-awscli:10.15
    environment:
      ENVIRONMENT: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - dev-dependencies-{{ checksum "package.json" }}
            - dev-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: dev-dependencies-{{ checksum "package.json" }}

      # Not using npm test because some behaviors are CI specific (junit for eslint and --ci for jest)
      - run: npx jest --ci --verbose test/
      - run: npx eslint . --format junit -o test-results/eslint/junit.xml

      - store_test_results:
          path: test-results

  deploy_dev:
    docker:
      - image: sleavely/node-awscli:10.15
    environment:
      ENVIRONMENT: dev
    steps:
      - checkout
      - restore_cache:
          keys:
            - dev-dependencies-{{ checksum "package.json" }}
            - dev-dependencies-
      - run: npm ci # need `juice` for deployments
      - run: make deploy
      - run:
          name: print failure events
          command: |
            aws cloudformation describe-stack-events --stack-name $PROJECT-$ENVIRONMENT |
            grep -B 7 -A 4 "\"Timestamp\": \"$(date +%Y-%m-%d)" |
            grep -A 2 -B 7 -E "\"ResourceStatus\": \".*FAILED\""
          when: on_fail

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy_dev:
          requires:
            - test
