version: 2
jobs:
  test:
    docker:
      - image: sleavely/node-awscli:10.x
    environment:
      ENVIRONMENT: test
    steps:
      - checkout

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: dev-dependencies-{{ checksum "package.json" }}

      # Not using npm test because some behaviors are CI specific (junit for eslint and --ci for jest)
      - run: npx jest --ci --verbose test/
      - run: npx eslint . --format junit -o test-results/eslint/junit.xml

      - store_test_results:
          path: test-results

  deploy_dev:
    docker:
      - image: sleavely/node-awscli:10.x
    environment:
      AWS_DEFAULT_REGION: eu-west-1
      ENVIRONMENT: dev
      PROJECT: geja
    steps:
      - checkout
      - restore_cache:
          keys:
            - dev-dependencies-{{ checksum "package.json" }}
            - dev-dependencies-

      - run: npm i # need `juice` for deployments

      - run: make deploy

      - run:
          name: Capture recent failure events
          command: |
            aws cloudformation describe-stack-events --stack-name $PROJECT-$ENVIRONMENT |
            grep -B 7 -A 4 "\"Timestamp\": \"$(date +%Y-%m-%d)" |
            grep -A 2 -B 7 -E "\"ResourceStatus\": \".*FAILED\"" > /tmp/cloudformation-failures.log
          when: on_fail

      - store_artifacts:
          path: /tmp/cloudformation-failures.log

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy_dev:
          requires:
            - test
