version: 2
jobs:
  test:
    docker:
      - image: sleavely/node-awscli:10.15
    environment:
      ENVIRONMENT: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - dev-dependencies-{{ checksum "package.json" }}
            - dev-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: dev-dependencies-{{ checksum "package.json" }}

      - run: npm test

  deploy_dev:
    docker:
      - image: sleavely/node-awscli:10.15
    environment:
      ENVIRONMENT: dev
    steps:
      - checkout
      - restore_cache:
          keys:
            - dev-dependencies-{{ checksum "package.json" }}
            - dev-dependencies-
      - run: npm ci # need `juice` for deployments
      - run: make deploy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy_dev:
          requires:
            - test
